import 'package:flutter/material.dart';
import '../models/service_model.dart';
import '../services/service_repository.dart';

class ServiceProvider with ChangeNotifier {
  final ServiceRepository _serviceRepository = ServiceRepository();

  Stream<List<Service>> get services => _serviceRepository.getServices();

  Future<void> addService(String name, String description, double price) async {
    final newService = Service(
      id: '', // ID will be generated by Firestore
      name: name,
      description: description,
      price: price,
    );
    await _serviceRepository.addService(newService);
  }

  Future<void> updateService(Service service) async {
    await _serviceRepository.updateService(service);
  }

  Future<void> deleteService(String serviceId) async {
    await _serviceRepository.deleteService(serviceId);
  }
}
